version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3
  ansible: orbss/ansible@0.2.3

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: execute cloudformation
          command: 
            aws cloudformation deploy --stack-name aws-study-cloudformation --template-file resources/AwsStudy.yaml

  execute-ansible:
    executor: ansible-playbook/default

workflows:
  CloudFormationTemplate:
    jobs:
      - execute-cloudformation
